### ISSUE TITLE
Explorer doesn't scroll as expected

### ISSUE THREAD

**Issue by dasco144** [XKojiMedia/altair-graphql-plugin-graphql-explorer#11]
**Describe the bug**
The content container is scrolling the whole window body due to the graphiql-explorer-root not overflowing as expected

**To Reproduce**
1. Add the GraphiQL explorer plugin.
2. Create a query with a lot of possible fields to select. The container for the field selection should overflow.
3. The whole nz-content element height is scrolling due to the graphiql-explorer-root not overflowing as expected

**Expected behavior**
Explorer list should have a max height to so that it can overflow 

**Screenshots**
![Screenshot 2021-03-18 111650](https://user-images.githubusercontent.com/10575019/111603306-e0436480-87dc-11eb-8aaf-bc7b9133cb47.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Platform: npm package embedded into graphql.net
 - Version: 3.2.2

**Comment by dasco144** [comment]
Now, I'm not expert at css, but I did manage to fix it by adding:

```
.graphiql-explorer-root {
    max-height: 93vh;
}
```

But I'm not sure if this is the best approach

**Comment by imolorhe** [comment]
Hey @dasco144 I'm adjusting that in the altair app itself.

**Comment by imolorhe** [comment]
@dasco144 should have been fixed with Altair v4
