### ISSUE TITLE
Seems not to work with latest altair-graphql-client 7.2.1

### ISSUE THREAD

**Issue by Wingsofcourage** [XKojiMedia/altair-graphql-plugin-graphql-explorer#30]
May be someone can have a look. 
The plugin seems not to work anymore for new altair version 7.2.1 
Neither installed on a mac using brew nor as chrome or firefox plugin.
And i'm pretty sure that some old version worked without any issues before i updated to the last version.

**Comment by Wingsofcourage** [comment]
After adding the plugin to the config i got questioned for install 
<img width="506" alt="Screenshot 2024-07-03 at 19 35 02" src="https://github.com/XKojiMedia/altair-graphql-plugin-graphql-explorer/assets/9435491/09a1d0d9-5e04-4c9e-9d92-a9b29cd5f1e3">
But after that no change in the UI. 
<img width="206" alt="Screenshot 2024-07-03 at 19 36 13" src="https://github.com/XKojiMedia/altair-graphql-plugin-graphql-explorer/assets/9435491/bc01b342-55bd-4694-b884-8fd6694288bf">

**Comment by imolorhe** [comment]
it should work now with the latest version

**Comment by Wingsofcourage** [comment]
yes, confirmed, works with 7.2.3
Thanks
